### PR TITLE
feat: Custom property types

### PR DESCRIPTION
**Pull request by lohnn**
This PR adds support for creating and adding custom property types.

### CODE REVIEW

**Review by erickzanardo — COMMENTED** [review]
Overall looks good to me! Could we just add a test for the new features?

**Comment by lohnn** [comment]
Absolutely! Was looking into adding tests, but as it added more boilerplate I settled with adding example. But I'll make sure to add tests as well ☺️

**Comment by spydon** [comment]
@lohnn if you update the branch now the pipeline should be fixed.

**Comment by lohnn** [comment]
Tests now added, you can now take one more look 👍

**Review by erickzanardo — APPROVED** [review]

**Pull request merged**
